In [48]:
import numpy as np
import random

# Version 1

df = np.zeros([5,5])
for x in range(len(df)):
    for z in range(len(df)):
        df[x, z] = random.randint(1,10)
print(df)
for x in range(len(df)):
    print(f"{x} row, sum: {sum(df[x])}")
for x in range(len(df)):
    print(f"{x} column, sum: {sum(df[:, x])}")

# Version 2

df = np.random.randint(1, 11, size=(5, 5))
print(df)
row_sums = np.sum(df, axis=1)
for i, row_sum in enumerate(row_sums):
    print(f"row {i}, sum: {row_sum}")
column_sums = np.sum(df, axis=0)
for i, column_sum in enumerate(column_sums):
    print(f"column {i}, sum: {column_sum}")


[[ 6. 10.  2.  1.  8.]
 [10.  3.  3.  6.  4.]
 [ 2.  9.  4.  5.  7.]
 [ 6.  3.  1. 10.  5.]
 [ 3.  5.  9.  7.  8.]]
0 row, sum: 27.0
1 row, sum: 26.0
2 row, sum: 27.0
3 row, sum: 25.0
4 row, sum: 32.0
0 column, sum: 27.0
1 column, sum: 30.0
2 column, sum: 19.0
3 column, sum: 29.0
4 column, sum: 32.0
[[ 2  4  4  1  7]
 [ 1 10  5  5  2]
 [ 1  7  7 10  1]
 [ 2  2  1  3  5]
 [ 7  6  2  1  1]]
Row 0, sum: 18
Row 1, sum: 23
Row 2, sum: 26
Row 3, sum: 13
Row 4, sum: 17
Column 0, sum: 13
Column 1, sum: 29
Column 2, sum: 19
Column 3, sum: 20
Column 4, sum: 16
